Stworzenie encji Product i Group
adrianpaz/project-jdp-2205-01 pull request #19
Opened 2022-05-09 04:24 UTC by Griksu

1. Stworzenie encji "PRODUCTS" dla klasy "Product" i zbudowanie relacji ManyToOne z encją "GROUPS"
2. Stworzenie encji "GROUPS" dla klasy "Group" i zbudowanie relacji OneToMany z encją "PRODUCTS"
3.  Zmodyfikowanie klas ProductDto i GroupDto
4.  Utworzenie pakiety repository i stworzenie interfejsu ProductRepository (na razie pusty)

2022-05-09 19:59 UTC, gkrajewski82 approved these changes

2022-05-09 22:00 UTC, VictorGoing approved these changes

2022-05-09 22:28 UTC, VictorGoing requested changes
Product powinien mieć jeszcze listę CartItem i OrderItem w relacjach OneToMany

2022-05-10 03:23 UTC, Griksu commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +@Data
Adnotacja "Data" łączy i zastępuje kilka innych, np. "Getter", "Setter", "ToString" itp. Więc zamiast wypisywać konkretne można napisać tylko "Data"

2022-05-10 17:03 UTC, VictorGoing commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +@Data
A myślałem że skupia się ona tylko na hashcodzie i equalsie. Dzięki za wyjaśnienie :)

2022-05-11 11:12 UTC, gkrajewski82 commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +@Setter
adnotacje @Setter nie są wymagane w naszym przypadku, gdy adnotacje dajemy nad polami, a nie getterami. Generalnie nie przeszkadza, ale nie jest potrzebna

2022-05-11 11:13 UTC, gkrajewski82 commented on src/main/java/com/kodilla/ecommercee/dto/CartDto.java
> +    private List<CartItem> cartItems;
Dlaczego zmieniłeś List<CartItemDto> na List<CartItem>? Nie można mieszać kompetencji, jak mamy Dto to posługujemy się obiektami Dto.

2022-05-11 11:14 UTC, gkrajewski82 commented on src/main/java/com/kodilla/ecommercee/dto/CartItemDto.java
> +    private Product product;
Analogicznie jak wyżej. W klasie Dto obiekty Dto

2022-05-11 11:15 UTC, gkrajewski82 commented on src/main/java/com/kodilla/ecommercee/dto/GroupDto.java
> +    private List<Product> products;
Dto

2022-05-11 11:17 UTC, gkrajewski82 commented on src/main/java/com/kodilla/ecommercee/dto/OrderItemDto.java
> +    private Product product;
Dto

2022-05-11 11:17 UTC, gkrajewski82 commented on src/main/java/com/kodilla/ecommercee/dto/ProductDto.java
> +    private Group group;
Dto

2022-05-11 14:15 UTC, Griksu commented on src/main/java/com/kodilla/ecommercee/dto/CartDto.java
> +    private List<CartItem> cartItems;
Wydaje mi się, że w powiązaniach pomiędzy obiektami typu DTO używa się klas / encji, ale nie mam pewności.
Mogę to zmienić przy rozwiązywaniu konfliktów jeżeli tak będzie lepiej.

2022-05-11 14:27 UTC, Griksu commented on src/main/java/com/kodilla/ecommercee/dto/CartItemDto.java
> +    private Product product;
OK, analogicznie jw

2022-05-11 14:27 UTC, Griksu commented on src/main/java/com/kodilla/ecommercee/dto/GroupDto.java
> +    private List<Product> products;
jw

2022-05-11 14:27 UTC, Griksu commented on src/main/java/com/kodilla/ecommercee/dto/ProductDto.java
> +    private Group group;
jw

2022-05-11 14:49 UTC, gkrajewski82 commented on src/main/java/com/kodilla/ecommercee/dto/CartDto.java
> +    private List<CartItem> cartItems;
Ja pamiętam z ostatniego spotkania, że Adrian powiedział właśnie, że nie mieszamy kompetencji i jak mamy klasę Dto to używamy obiektów DTO.

2022-05-11 17:13 UTC, Griksu commented on src/main/java/com/kodilla/ecommercee/dto/CartDto.java
> +    private List<CartItem> cartItems;
OK

2022-05-11 22:24 UTC, gkrajewski82 approved these changes

2022-05-12 11:01 UTC, jarekwarowny approved these changes

2022-05-12 14:49 UTC, VictorGoing approved these changes
Sorki nie wiedziałem że Cię to przytrzyma

2022-05-12 16:17 UTC, merged